name: Build and Deploy

on:
  push:
    branches:
      - dev # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Test the app
        run: npm run test

      - name: Deploy to production
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages # Change this to your deployment branch
          folder: out # Change this to your build folder
